import 'dart:convert';
import 'package:flutter/services.dart';
import '../models/banking_card_model.dart';
import '../models/brand_model.dart';

class BankingCardService {
  static const String _assetPath = 'assets/data/banking_cards.json';

  /// Loads credit cards dynamically from the local JSON asset.
  Future<List<BankingCardModel>> loadCards() async {
    try {
      final jsonString = await rootBundle.loadString(_assetPath);
      final List<dynamic> jsonList = jsonDecode(jsonString) as List<dynamic>;
      return jsonList
          .map((item) => BankingCardModel.fromJson(item as Map<String, dynamic>))
          .toList();
    } catch (e) {
      return fallbackCards;
    }
  }

  /// Loads cards formatted as [BrandModel] so they can be dropped into existing brand grids.
  Future<List<BrandModel>> loadAsBrands() async {
    final cards = await loadCards();
    return cards.map((c) => c.toBrandModel()).toList();
  }

  /// Static fallback list of all 20 credit cards with local assets and details.
  static const List<BankingCardModel> fallbackCards = [
    BankingCardModel(
      id: '24756',
      slug: 'sbi-cashback-card',
      name: 'SBI Cashback Credit Card',
      tag: 'Best Cashback Card',
      rewardAmount: '₹1400',
      rewardType: 'Rewards',
      cashbackText: 'Flat ₹1400 Rewards',
      shortDescription: 'Cash in on Online Payments with SBI ☛ 5% Cashback on Online Spends ☛ 1% Cashback on Offline Spends ☛ Save Upto Rs.60,000 Annually + Flat Rs.1500 CashKaro Rewards on Credit Card Activation',
      perks: ['5% Cashback on Online Spends', '1% Cashback on Offline Spends', 'Save Upto Rs.60,000 Annually'],
      remoteImageUrl: 'https://asset21.ckassets.com/resources/image/stores/sbi-cashback-card-1759465154.png',
      localAssetPath: 'assets/cards/sbi-cashback-card.png',
      applyUrl: 'https://tracking.cashkaro.com/visitretailer/24756?id=',
    ),
    BankingCardModel(
      id: '26031',
      slug: 'axis-neo-rupay-credit-card',
      name: 'Axis Neo Rupay Credit Card',
      tag: 'Lifetime Free',
      rewardAmount: '₹960',
      rewardType: 'Rewards',
      cashbackText: 'Flat ₹960 Rewards',
      shortDescription: 'Lifetime Free RuPay card with instant discounts on entertainment, dining, and utility bill payments.',
      perks: ['Lifetime Free Credit Card', '10% off on BookMyShow movie tickets', '5% off on utility payments via Amazon Pay', 'UPI payments enabled via RuPay network'],
      remoteImageUrl: 'https://asset21.ckassets.com/resources/image/stores/axis-neo-rupay-credit-card-1761629159.jpg',
      localAssetPath: 'assets/cards/axis-neo-rupay-credit-card.jpg',
      applyUrl: 'https://tracking.cashkaro.com/visitretailer/26031?id=',
    ),
    BankingCardModel(
      id: '24745',
      slug: 'hsbc-platinum-credit-card',
      name: 'HSBC Platinum Credit Card',
      tag: 'Lifetime Free',
      rewardAmount: '₹2000',
      rewardType: 'Rewards',
      cashbackText: 'Flat ₹2000 Rewards',
      shortDescription: 'Unlock Platinum Rewards with HSBC ☛ Lifetime FREE ☛ 2 Reward Points per every Rs.150 Spent ☛ 5x Reward Points on Milestone Spends + Flat Rs.2200 CashKaro Rewards on Credit Card Activation',
      perks: ['Lifetime FREE', '2 Reward Points per every Rs.150 Spent', '5x Reward Points on Milestone Spends'],
      remoteImageUrl: 'https://asset21.ckassets.com/resources/image/stores/hsbc-platinum-credit-card-1760087739.png',
      localAssetPath: 'assets/cards/hsbc-platinum-credit-card.png',
      applyUrl: 'https://tracking.cashkaro.com/visitretailer/24745?id=',
    ),
    BankingCardModel(
      id: '26525',
      slug: 'uni-goldx-credit-card',
      name: 'Uni GoldX Credit Card',
      tag: 'Lifetime Free',
      rewardAmount: '₹1000',
      rewardType: 'Rewards',
      cashbackText: 'Flat ₹1000 Rewards',
      shortDescription: 'Earn 1% pure 24K digital gold on all transactions with no joining or annual renewal charges.',
      perks: ['Lifetime Free with zero joining fee', '1% Pure 24K Digital Gold on all spends', 'Zero foreign transaction mark-up fees', 'Instant digital onboarding & virtual card'],
      remoteImageUrl: 'https://asset21.ckassets.com/resources/image/stores/uni-goldx-credit-card-1778750640.png',
      localAssetPath: 'assets/cards/uni-goldx-credit-card.png',
      applyUrl: 'https://tracking.cashkaro.com/visitretailer/26525?id=',
    ),
    BankingCardModel(
      id: '24742',
      slug: 'federal-bank-scapia-credit-card-offer',
      name: 'Scapia Co-Branded Credit Card',
      tag: 'Best Travel Card',
      rewardAmount: '₹650',
      rewardType: 'Rewards',
      cashbackText: 'Flat ₹650 Rewards',
      shortDescription: 'Explore more, spend less - with the Scapia Co-Branded Credit Card! Get 10% back as Scapia Coins on eligible spends, unlimited domestic lounge access, and zero forex markup -- all with no annual fees. Travel enthusiasts, apply via CashKaro today and enjoy extra Rewards on successful approval on Card Activation',
      perks: ['Explore more, spend less - with the Scapia Co-Branded Credit Card! Get 10% back as Scapia Coins on eligible spends, unlimited domestic lounge access, and zero forex markup -- all with no annual fees', 'Travel enthusiasts, apply via CashKaro today and enjoy extra Rewards on successful approval on Card Activation'],
      remoteImageUrl: 'https://asset21.ckassets.com/resources/image/stores/federal-bank-scapia-credit-card-offer-1770186828.png',
      localAssetPath: 'assets/cards/federal-bank-scapia-credit-card-offer.png',
      applyUrl: 'https://tracking.cashkaro.com/visitretailer/24742?id=',
    ),
    BankingCardModel(
      id: '18487',
      slug: 'flipkart-sbi-credit-card',
      name: 'SBI Flipkart Credit Card',
      tag: 'Best for Flipkart',
      rewardAmount: '₹1200',
      rewardType: 'Rewards',
      cashbackText: 'Flat ₹1200 Rewards',
      shortDescription: 'Direct savings and high reward points on Flipkart, Cleartrip, and popular digital platforms.',
      perks: ['5% Unlimited Cashback on Flipkart purchases', '4% Cashback on preferred merchants (Swiggy, Uber)', '1% Cashback on all other offline & online spends', 'Complimentary domestic airport lounge visits'],
      remoteImageUrl: 'https://asset21.ckassets.com/resources/image/stores/sbi-flipkart-credit-card-1767875438.png',
      localAssetPath: 'assets/cards/flipkart-sbi-credit-card.png',
      applyUrl: 'https://tracking.cashkaro.com/visitretailer/18487?id=',
    ),
    BankingCardModel(
      id: '24715',
      slug: 'idfc-first-credit-card',
      name: 'IDFC First Credit Card',
      tag: 'Lifetime Free',
      rewardAmount: '₹700',
      rewardType: 'Rewards',
      cashbackText: 'Flat ₹700 Rewards',
      shortDescription: 'Best Lifetime Free Cards! ☛ Lifetime FREE - No joining or annual fee ☛ Reward Point NEVER Expire - Unique Feature ☛ No interest on ATM withdrawals till 48 days + Upto Rs.750 CashKaro Rewards on Credit Card Activation',
      perks: ['Lifetime FREE - No joining or annual fee', 'Reward Point NEVER Expire - Unique Feature', 'No interest on ATM withdrawals till 48 days'],
      remoteImageUrl: 'https://asset21.ckassets.com/resources/image/stores/idfc-first-credit-card-1741857744.png',
      localAssetPath: 'assets/cards/idfc-first-credit-card.png',
      applyUrl: 'https://tracking.cashkaro.com/visitretailer/24715?id=',
    ),
    BankingCardModel(
      id: '25861',
      slug: 'bobcard-eterna-credit-card',
      name: 'BOBCARD Eterna Credit Card',
      tag: 'First Year Free',
      rewardAmount: '₹540',
      rewardType: 'Rewards',
      cashbackText: 'Flat ₹540 Rewards',
      shortDescription: 'Premium lifestyle credit card offering unlimited lounge access and accelerated rewards on dining & travel.',
      perks: ['Unlimited Domestic Airport Lounge Access', '3 Reward Points per ₹100 on dining & travel', 'Complimentary movie ticket per month on Paytm', '1% Fuel Surcharge waiver across all stations'],
      remoteImageUrl: 'https://asset21.ckassets.com/resources/image/stores/bobcard-eterna-credit-card-1763982656.png',
      localAssetPath: 'assets/cards/bobcard-eterna-credit-card.png',
      applyUrl: 'https://tracking.cashkaro.com/visitretailer/25861?id=',
    ),
    BankingCardModel(
      id: '10043151',
      slug: 'yes-bank-popclub-credit-card',
      name: 'Yes Bank Pop-Club Credit Card',
      tag: 'Lifetime Free',
      rewardAmount: '₹1000',
      rewardType: 'Rewards',
      cashbackText: 'Flat ₹1000 Rewards',
      shortDescription: 'India most Rewarding RuPay credit card ☛ Lifetime FREE ☛ Rs.5000 worth of Joining Benefits ☛Get POPcoins on every transaction ☛Up to 2.5% Cashback on coins conversion to vouchers + Flat Rs.1100 CashKaro Rewards on Credit Card Activation',
      perks: ['Lifetime FREE', 'Rs.5000 worth of Joining Benefits', 'Get POPcoins on every transaction', 'Up to 2.5% Cashback on coins conversion to vouchers '],
      remoteImageUrl: 'https://asset21.ckassets.com/resources/image/stores/yes-bank-popclub-credit-card-1771480308.png',
      localAssetPath: 'assets/cards/yes-bank-popclub-credit-card.png',
      applyUrl: 'https://tracking.cashkaro.com/visitretailer/10043151?id=',
    ),
    BankingCardModel(
      id: '10043150',
      slug: 'kiwi-credit-card-offers',
      name: 'UPI Credit Card on KIWI',
      tag: 'Save on UPI',
      rewardAmount: '₹1000',
      rewardType: 'Rewards',
      cashbackText: 'Flat ₹1000 Rewards',
      shortDescription: 'Virtual RuPay credit card designed specifically for scan-and-pay UPI transactions with flat 1.5% cashback.',
      perks: ['Flat 1.5% Edge Rewards on UPI scan & pay transactions', 'Virtual issuance in under 2 minutes', 'Zero annual fee and zero joining fee', 'Cashback directly credited to linked bank account'],
      remoteImageUrl: 'https://asset21.ckassets.com/resources/image/stores/kiwi-credit-card-offers-1759329211.png',
      localAssetPath: 'assets/cards/kiwi-credit-card-offers.png',
      applyUrl: 'https://tracking.cashkaro.com/visitretailer/10043150?id=',
    ),
    BankingCardModel(
      id: '19878',
      slug: 'kotak-league-platinum-credit-card',
      name: 'Kotak League Platinum Credit Card',
      tag: 'Lifetime Free',
      rewardAmount: '₹800',
      rewardType: 'Rewards',
      cashbackText: 'Flat ₹800 Rewards',
      shortDescription: 'custom> The Kotak League Platinum Credit Card enhances everyday spending with up to 8 reward points per Rs.150 across categories, fuel surcharge waivers, railway surcharge benefits, priority assistance, and fraud protection for a secure and rewarding experience. Apply via CashKaro to earn extra Rewards on successful activation on Credit Card Activation',
      perks: ['custom> The Kotak League Platinum Credit Card enhances everyday spending with up to 8 reward points per Rs', '150 across categories, fuel surcharge waivers, railway surcharge benefits, priority assistance, and fraud protection for a secure and rewarding experience', 'Apply via CashKaro to earn extra Rewards on successful activation on Credit Card Activation'],
      remoteImageUrl: 'https://asset21.ckassets.com/resources/image/stores/kotak-league-platinum-credit-card-1774347914.png',
      localAssetPath: 'assets/cards/kotak-league-platinum-credit-card.png',
      applyUrl: 'https://tracking.cashkaro.com/visitretailer/19878?id=',
    ),
    BankingCardModel(
      id: '24732',
      slug: 'indusind-tiger-credit',
      name: 'Indusind Tiger Credit Card',
      tag: 'Lifetime Free',
      rewardAmount: '₹500',
      rewardType: 'Rewards',
      cashbackText: 'Flat ₹500 Rewards',
      shortDescription: 'Lifetime FREE - No Joining or Annual Fees ☛ Earn Upto 6 Reward Points (1 Reward Point = 1.2 Airmiles) on every Rs 100 spent ☛ 2 Domestic and 2 International Lounge access per year ☛ One complimentary movie ticket upto Rs.500 on BookMyShow every 6 months ☛ 1.50% Discounted Forex Mark-up Fee + Flat Rs.300 CashKaro Rewards on Credit Card Activation',
      perks: ['Earn Upto 6 Reward Points (1 Reward Point = 1.2 Airmiles) on every Rs 100 spent', '2 Domestic and 2 International Lounge access per year', 'One complimentary movie ticket upto Rs.500 on BookMyShow every 6 months', '1.50% Discounted Forex Mark-up Fee'],
      remoteImageUrl: 'https://asset21.ckassets.com/resources/image/stores/indusind-tiger-credit-card-1740289352.png',
      localAssetPath: 'assets/cards/indusind-tiger-credit.png',
      applyUrl: 'https://tracking.cashkaro.com/visitretailer/24732?id=',
    ),
    BankingCardModel(
      id: '24759',
      slug: 'simply-click-sbi-card',
      name: 'SBI Simply Click Credit Card',
      tag: 'Amazon Sale Saver',
      rewardAmount: '₹1200',
      rewardType: 'Rewards',
      cashbackText: 'Flat ₹1200 Rewards',
      shortDescription: 'Dedicated e-commerce card offering 10X reward points on Amazon, Cleartrip, BookMyShow, and Netmeds.',
      perks: ['10X Reward Points on Amazon, Cleartrip & BookMyShow', '5X Reward Points on all other online spends', '₹500 Amazon gift voucher on joining', 'Annual fee reversal on spends over ₹1,00,000'],
      remoteImageUrl: 'https://asset21.ckassets.com/resources/image/stores/simply-click-sbi-card-1740289499.png',
      localAssetPath: 'assets/cards/simply-click-sbi-card.png',
      applyUrl: 'https://tracking.cashkaro.com/visitretailer/24759?id=',
    ),
    BankingCardModel(
      id: '26940',
      slug: 'cub-salaryse-level-up-credit-card',
      name: 'SalarySe',
      tag: 'Lifetime Free',
      rewardAmount: '₹900',
      rewardType: 'Rewards',
      cashbackText: 'Flat ₹900 Rewards',
      shortDescription: 'Next-generation credit card on UPI for salaried employees with instant credit line on salary.',
      perks: ['Lifetime Free with no annual maintenance charges', 'Scan & Pay via UPI with instant rewards', 'Rewards on bill payments, recharges, and groceries', 'Seamless salary-linked limit enhancement'],
      remoteImageUrl: 'https://asset21.ckassets.com/resources/image/stores/salaryse-coupons-test-1783665209.png',
      localAssetPath: 'assets/cards/cub-salaryse-level-up-credit-card.png',
      applyUrl: 'https://tracking.cashkaro.com/visitretailer/26940?id=',
    ),
    BankingCardModel(
      id: '24654',
      slug: 'bank-karo-axis-flipkart',
      name: 'Axis Flipkart Credit Card',
      tag: 'Best for Flipkart',
      rewardAmount: '₹960',
      rewardType: 'Rewards',
      cashbackText: 'Flat ₹960 Rewards',
      shortDescription: 'Best Credit Card for Flipkart Shopping ☛ UNLIMITED 5% Cashback on Flipkart & Cleartrip! ☛ 4% Cashback on Swiggy & preferred merchants ☛ 1% Cashback on Everything else! + Flat Rs.1400 CashKaro Rewards on Credit Card Activation',
      perks: ['UNLIMITED 5% Cashback on Flipkart  & Cleartrip!', '4% Cashback on Swiggy & preferred merchants', '1% Cashback on Everything else!'],
      remoteImageUrl: 'https://asset21.ckassets.com/resources/image/stores/bank-karo-axis-flipkart-1759675165.png',
      localAssetPath: 'assets/cards/bank-karo-axis-flipkart.png',
      applyUrl: 'https://tracking.cashkaro.com/visitretailer/24654?id=',
    ),
    BankingCardModel(
      id: '24746',
      slug: 'rbl-bank-shoprite-credit',
      name: 'RBL Bank Shoprite Credit Card',
      tag: 'Lifetime Free',
      rewardAmount: '₹700',
      rewardType: 'Rewards',
      cashbackText: 'Flat ₹700 Rewards',
      shortDescription: 'Save on Everyday Grocery Spends ☛Lifetime FREE ☛ Amazing offers on Zomato, Swiggy, Zepto, Tata Cliq and more ☛ 20 Reward points for every Rs.100 spent on groceries ☛ 10% discount (up to Rs.100) on movie tickets on BookMyShow + Flat Rs.750 CashKaro Rewards on Credit Card Activation',
      perks: ['Lifetime FREE', 'Amazing offers on Zomato, Swiggy, Zepto, Tata Cliq and more', '20 Reward points for every Rs.100 spent on groceries', '10% discount (up to Rs.100) on movie tickets on BookMyShow'],
      remoteImageUrl: 'https://asset21.ckassets.com/resources/image/stores/rbl-bank-shoprite-credit-card-1740289410.png',
      localAssetPath: 'assets/cards/rbl-bank-shoprite-credit.png',
      applyUrl: 'https://tracking.cashkaro.com/visitretailer/24746?id=',
    ),
    BankingCardModel(
      id: '19714',
      slug: 'tata-neu-infinity-sbi-credit-card',
      name: 'Tata Neu Infinity SBI Credit Card',
      tag: '10% NeuCoins',
      rewardAmount: '₹1200',
      rewardType: 'Rewards',
      cashbackText: 'Flat ₹1200 Rewards',
      shortDescription: 'Premium Tata Neu co-branded card offering 10% NeuCoins on Tata Neu and Tata brands.',
      perks: ['10% NeuCoins on Tata Neu app purchases', '5% NeuCoins on non-EMI Tata brand spends', '8 complimentary domestic and 4 international lounge visits', '1 NeuCoin = ₹1 spendable across Air India, Croma, BigBasket, Westside'],
      remoteImageUrl: 'https://asset21.ckassets.com/resources/image/stores/tata-neu-infinity-sbi-credit-card-1773726015.png',
      localAssetPath: 'assets/cards/tata-neu-infinity-sbi-credit-card.png',
      applyUrl: 'https://tracking.cashkaro.com/visitretailer/19714?id=',
    ),
    BankingCardModel(
      id: '19723',
      slug: 'tata-neu-plus-sbi-credit-card',
      name: 'Tata Neu Plus SBI Credit Card',
      tag: '7% NeuCoins',
      rewardAmount: '₹1200',
      rewardType: 'Rewards',
      cashbackText: 'Flat ₹1200 Rewards',
      shortDescription: 'Smart everyday card with up to 7% NeuCoins on groceries, electronics, and Tata ecosystem spends.',
      perks: ['7% NeuCoins on Tata Neu app purchases', '2% NeuCoins on partner Tata brands', '4 complimentary domestic airport lounge visits per year', '1% Fuel surcharge waiver'],
      remoteImageUrl: 'https://asset21.ckassets.com/resources/image/stores/tata-neu-plus-sbi-credit-card-1773726607.png',
      localAssetPath: 'assets/cards/tata-neu-plus-sbi-credit-card.png',
      applyUrl: 'https://tracking.cashkaro.com/visitretailer/19723?id=',
    ),
    BankingCardModel(
      id: '24741',
      slug: 'hsbc-live-plus-credit-card',
      name: 'HSBC Live Plus Credit Card',
      tag: 'Best for Grocery',
      rewardAmount: '₹2000',
      rewardType: 'Rewards',
      cashbackText: 'Flat ₹2000 Rewards',
      shortDescription: 'Industry-leading 10% cashback on groceries, food delivery, and dining across India.',
      perks: ['10% Accelerated Cashback on dining, food delivery & groceries', '1.5% Unlimited Cashback on all other eligible spends', 'Complimentary domestic airport lounge access', 'Dining discount privileges up to 15% across major cities'],
      remoteImageUrl: 'https://asset21.ckassets.com/resources/image/stores/hsbc-live-plus-credit-card-1740289013.png',
      localAssetPath: 'assets/cards/hsbc-live-plus-credit-card.png',
      applyUrl: 'https://tracking.cashkaro.com/visitretailer/24741?id=',
    ),
    BankingCardModel(
      id: '24660',
      slug: 'bank-karo-axis-my-zone',
      name: 'Axis MyZone Rupay Credit Card',
      tag: 'BOGO Movies',
      rewardAmount: '₹1120',
      rewardType: 'Rewards',
      cashbackText: 'Flat ₹1120 Rewards',
      shortDescription: 'Pocket-friendly entertainment card with Buy 1 Get 1 Free on movie tickets and flat discounts on Swiggy.',
      perks: ['Buy 1 Get 1 Free on Paytm Movies (up to ₹200 off)', 'Flat ₹120 off on Swiggy food orders twice a month', 'Complimentary domestic airport lounge access per quarter', 'UPI payments enabled via RuPay network'],
      remoteImageUrl: 'https://asset21.ckassets.com/resources/image/stores/bank-karo-axis-my-zone-1740288393.png',
      localAssetPath: 'assets/cards/bank-karo-axis-my-zone.png',
      applyUrl: 'https://tracking.cashkaro.com/visitretailer/24660?id=',
    ),
  ];
}
