import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;
import '../models/home_discovery_models.dart';
import 'app_cashback_engine.dart';
import 'auth_service.dart';

class HomeService {
  final http.Client _client;

  HomeService({http.Client? client}) : _client = client ?? http.Client();

  /// Fetches structured home discovery feed from Node.js backend
  /// (GET /api/home) with seamless offline fallback.
  Future<HomeDataModel> fetchHomeData() async {
    try {
      final uri = Uri.parse('${AuthService.baseUrl}/home');
      final response = await _client.get(uri).timeout(
            const Duration(seconds: 3),
          );

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body) as Map<String, dynamic>;
        if (data['success'] == true && data['data'] != null) {
          return HomeDataModel.fromJson(data['data'] as Map<String, dynamic>);
        }
      }
    } catch (e) {
      debugPrint('HomeService: Network fetch unavailable, using offline cache/data: $e');
    }

    // Return structured default data if remote backend is offline
    return getFallbackHomeData();
  }

  /// Offline discovery dataset. Best deals go through the same cashback
  /// stacking and ranking as the backend smart deal engine, so offline cards
  /// show the cashback KashIQ actually pays (brand prices/offers unchanged).
  static HomeDataModel getFallbackHomeData() {
    final raw = _rawFallbackHomeData();
    final deals = raw.bestDeals.map(_withAppCashback).toList()
      ..sort((a, b) {
        final bySavings = _savingsPercent(b).compareTo(_savingsPercent(a));
        return bySavings != 0 ? bySavings : a.effectivePrice.compareTo(b.effectivePrice);
      });

    return HomeDataModel(
      cashbackSummary: raw.cashbackSummary,
      bestDeals: deals,
      offers: raw.offers,
      coupons: raw.coupons,
      smartSavings: raw.smartSavings,
      featuredStores: raw.featuredStores,
      trendingDeals: raw.trendingDeals,
      priceDrops: raw.priceDrops,
      cashbackIncreases: raw.cashbackIncreases,
      bestDealsPage: raw.bestDealsPage,
    );
  }

  static double _savingsPercent(BestDealModel d) =>
      d.originalPrice > 0 ? (d.effectiveSavings / d.originalPrice * 100).roundToDouble() : 0;

  static BestDealModel _withAppCashback(BestDealModel deal) {
    var stores = deal.stores.map((st) {
      final r = AppCashbackEngine.calculate(
        store: st.store,
        originalPrice: deal.originalPrice,
        storePrice: st.price,
        couponDiscount: st.coupon,
      );
      return StoreDealComparison(
        store: st.store,
        price: st.price,
        storeDiscount: st.storeDiscount,
        cashback: r.cashbackAmount,
        coupon: st.coupon,
        effectivePrice: r.effectivePrice,
        savings: r.effectiveSavings,
        isBest: false,
      );
    }).toList();

    // Lowest effective price wins, like compareAndPickBestStore()
    stores.sort((a, b) => a.effectivePrice.compareTo(b.effectivePrice));
    stores = [
      for (var i = 0; i < stores.length; i++)
        i == 0
            ? StoreDealComparison(
                store: stores[i].store,
                price: stores[i].price,
                storeDiscount: stores[i].storeDiscount,
                cashback: stores[i].cashback,
                coupon: stores[i].coupon,
                effectivePrice: stores[i].effectivePrice,
                savings: stores[i].savings,
                isBest: true,
              )
            : stores[i],
    ];

    final bestStore = stores.isNotEmpty ? stores.first.store : deal.store;
    final price = stores.isNotEmpty ? stores.first.price : deal.discountedPrice;
    final coupon = stores.isNotEmpty ? stores.first.coupon : deal.couponDiscount;
    final r = AppCashbackEngine.calculate(
      store: bestStore,
      originalPrice: deal.originalPrice,
      storePrice: price,
      couponDiscount: coupon,
    );

    return BestDealModel(
      id: deal.id,
      title: deal.title,
      brand: deal.brand,
      store: bestStore,
      imageUrl: deal.imageUrl,
      originalPrice: deal.originalPrice,
      discountedPrice: price,
      discountPercentage: deal.originalPrice > 0
          ? ((deal.originalPrice - price) / deal.originalPrice * 100).roundToDouble()
          : 0,
      cashbackPercentage: r.cashbackPercentage,
      cashbackAmount: r.cashbackAmount,
      couponCode: deal.couponCode,
      couponDiscount: coupon,
      effectiveSavings: r.effectiveSavings,
      effectivePrice: r.effectivePrice,
      isBestDeal: deal.isBestDeal,
      badge: deal.badge,
      category: deal.category,
      storesAvailable: deal.storesAvailable,
      stores: stores,
    );
  }

  /// High quality offline discovery dataset using local assets in assets/cards/, assets/banners/, assets/logos/
  static HomeDataModel _rawFallbackHomeData() {
    return HomeDataModel(
      cashbackSummary: const CashbackSummaryModel(
        availableCashback: 1540.0,
        pendingCashback: 676.0,
        totalSavings: 2216.0,
      ),
      bestDeals: const [
        BestDealModel(
          id: 'prod-nike-270',
          title: 'Nike Air Max 270',
          brand: 'Nike',
          store: 'Myntra',
          imageUrl: 'assets/banners/nike_airmax_red.jpg',
          originalPrice: 5999,
          discountedPrice: 4155,
          discountPercentage: 30,
          cashbackPercentage: 10,
          cashbackAmount: 415,
          couponCode: 'NIKE20',
          couponDiscount: 300,
          effectiveSavings: 2559,
          effectivePrice: 3440,
          isBestDeal: true,
          badge: '🏆 Best Deal',
          category: 'Footwear',
          storesAvailable: ['Myntra', 'Flipkart', 'Amazon'],
          stores: [
            StoreDealComparison(
              store: 'Myntra',
              price: 4155,
              storeDiscount: 1844,
              cashback: 415,
              coupon: 300,
              effectivePrice: 3440,
              savings: 2559,
              isBest: true,
            ),
            StoreDealComparison(
              store: 'Flipkart',
              price: 4499,
              storeDiscount: 1500,
              cashback: 350,
              coupon: 200,
              effectivePrice: 3949,
              savings: 2050,
              isBest: false,
            ),
            StoreDealComparison(
              store: 'Amazon',
              price: 4799,
              storeDiscount: 1200,
              cashback: 250,
              coupon: 150,
              effectivePrice: 4399,
              savings: 1600,
              isBest: false,
            ),
          ],
        ),
        BestDealModel(
          id: 'prod-4',
          title: 'iPhone 15',
          brand: 'Apple',
          store: 'Flipkart',
          imageUrl: 'assets/banners/phone_banner_16_9.jpg',
          originalPrice: 79900,
          discountedPrice: 70999,
          discountPercentage: 11,
          cashbackPercentage: 4,
          cashbackAmount: 2500,
          couponCode: 'IPHONE2000',
          couponDiscount: 2000,
          effectiveSavings: 13401,
          effectivePrice: 66499,
          isBestDeal: true,
          badge: '🏆 Best Deal',
          category: 'Smartphones',
          storesAvailable: ['Flipkart', 'Amazon', 'Croma'],
          stores: [
            StoreDealComparison(
              store: 'Flipkart',
              price: 70999,
              storeDiscount: 8901,
              cashback: 2500,
              coupon: 2000,
              effectivePrice: 66499,
              savings: 13401,
              isBest: true,
            ),
            StoreDealComparison(
              store: 'Amazon',
              price: 71999,
              storeDiscount: 7901,
              cashback: 2000,
              coupon: 1500,
              effectivePrice: 68499,
              savings: 11401,
              isBest: false,
            ),
            StoreDealComparison(
              store: 'Croma',
              price: 73900,
              storeDiscount: 6000,
              cashback: 1500,
              coupon: 1000,
              effectivePrice: 71400,
              savings: 8500,
              isBest: false,
            ),
          ],
        ),
        BestDealModel(
          id: 'prod-2',
          title: 'MacBook Air M2',
          brand: 'Apple',
          store: 'Amazon',
          imageUrl: 'assets/cards/dell.jpg',
          originalPrice: 99900,
          discountedPrice: 84990,
          discountPercentage: 15,
          cashbackPercentage: 5,
          cashbackAmount: 4250,
          couponCode: 'MACBOOK3000',
          couponDiscount: 3000,
          effectiveSavings: 22160,
          effectivePrice: 77740,
          isBestDeal: true,
          badge: '🏆 Best Deal',
          category: 'Laptops',
          storesAvailable: ['Amazon', 'Reliance Digital', 'Flipkart'],
          stores: [
            StoreDealComparison(
              store: 'Amazon',
              price: 84990,
              storeDiscount: 14910,
              cashback: 4250,
              coupon: 3000,
              effectivePrice: 77740,
              savings: 22160,
              isBest: true,
            ),
            StoreDealComparison(
              store: 'Reliance Digital',
              price: 86900,
              storeDiscount: 13000,
              cashback: 3000,
              coupon: 2000,
              effectivePrice: 81900,
              savings: 18000,
              isBest: false,
            ),
            StoreDealComparison(
              store: 'Flipkart',
              price: 88990,
              storeDiscount: 10910,
              cashback: 2500,
              coupon: 1500,
              effectivePrice: 84990,
              savings: 14910,
              isBest: false,
            ),
          ],
        ),
        BestDealModel(
          id: 'prod-3',
          title: 'Galaxy S24 Ultra',
          brand: 'Samsung',
          store: 'Samsung',
          imageUrl: 'assets/banners/phone_banner_16_9.jpg',
          originalPrice: 129999,
          discountedPrice: 119999,
          discountPercentage: 8,
          cashbackPercentage: 4,
          cashbackAmount: 4800,
          couponCode: 'SAM5000',
          couponDiscount: 5000,
          effectiveSavings: 19800,
          effectivePrice: 110199,
          isBestDeal: true,
          badge: '🏆 Best Deal',
          category: 'Smartphones',
          storesAvailable: ['Samsung', 'Amazon', 'Flipkart'],
          stores: [
            StoreDealComparison(
              store: 'Samsung',
              price: 119999,
              storeDiscount: 10000,
              cashback: 4800,
              coupon: 5000,
              effectivePrice: 110199,
              savings: 19800,
              isBest: true,
            ),
            StoreDealComparison(
              store: 'Amazon',
              price: 121999,
              storeDiscount: 8000,
              cashback: 3500,
              coupon: 3000,
              effectivePrice: 115499,
              savings: 14500,
              isBest: false,
            ),
            StoreDealComparison(
              store: 'Flipkart',
              price: 124999,
              storeDiscount: 5000,
              cashback: 3000,
              coupon: 2000,
              effectivePrice: 119999,
              savings: 10000,
              isBest: false,
            ),
          ],
        ),
        BestDealModel(
          id: 'prod-boat-1',
          title: 'boAt Rockerz 450',
          brand: 'boAt',
          store: 'Flipkart',
          imageUrl: 'assets/cards/boat-coupon.jpg',
          originalPrice: 3990,
          discountedPrice: 1499,
          discountPercentage: 62,
          cashbackPercentage: 8,
          cashbackAmount: 120,
          couponCode: 'BOAT200',
          couponDiscount: 200,
          effectiveSavings: 2811,
          effectivePrice: 1179,
          isBestDeal: true,
          badge: '🏆 Top Value',
          category: 'Audio',
          storesAvailable: ['Flipkart', 'Amazon'],
        ),
        BestDealModel(
          id: 'prod-derma-1',
          title: 'Vitamin C Face Serum',
          brand: 'The Derma Co',
          store: 'Nykaa',
          imageUrl: 'assets/cards/thedermaco-coupons.jpg',
          originalPrice: 649,
          discountedPrice: 519,
          discountPercentage: 20,
          cashbackPercentage: 15,
          cashbackAmount: 78,
          couponCode: 'DERMA100',
          couponDiscount: 100,
          effectiveSavings: 308,
          effectivePrice: 341,
          isBestDeal: true,
          badge: '🏆 Best Deal',
          category: 'Beauty',
          storesAvailable: ['Nykaa', 'Amazon'],
        ),
        BestDealModel(
          id: 'prod-dotkey-1',
          title: 'Ceramide Repair Cream',
          brand: 'Dot & Key',
          store: 'Amazon',
          imageUrl: 'assets/cards/dotandkey-coupons.png',
          originalPrice: 595,
          discountedPrice: 449,
          discountPercentage: 24,
          cashbackPercentage: 12,
          cashbackAmount: 54,
          couponCode: 'DOTKEY50',
          couponDiscount: 50,
          effectiveSavings: 250,
          effectivePrice: 345,
          isBestDeal: true,
          badge: '🏆 Top Value',
          category: 'Beauty',
          storesAvailable: ['Amazon', 'Nykaa'],
        ),
        BestDealModel(
          id: 'prod-levis-1',
          title: 'Denim Plaid Shirt',
          brand: 'Levi\'s',
          store: 'Myntra',
          imageUrl: 'assets/cards/col_myntra.jpg',
          originalPrice: 2999,
          discountedPrice: 1799,
          discountPercentage: 40,
          cashbackPercentage: 10,
          cashbackAmount: 180,
          couponCode: 'LEVI300',
          couponDiscount: 300,
          effectiveSavings: 1500,
          effectivePrice: 1319,
          isBestDeal: true,
          badge: '🏆 Best Deal',
          category: 'Fashion',
          storesAvailable: ['Myntra', 'AJIO'],
        ),
        BestDealModel(
          id: 'prod-noise-1',
          title: 'ColorFit Pro 5',
          brand: 'Noise',
          store: 'Amazon',
          imageUrl: 'assets/cards/gonoise-coupons.jpg',
          originalPrice: 7999,
          discountedPrice: 3499,
          discountPercentage: 56,
          cashbackPercentage: 6,
          cashbackAmount: 210,
          couponCode: 'NOISE300',
          couponDiscount: 300,
          effectiveSavings: 5010,
          effectivePrice: 2989,
          isBestDeal: true,
          badge: '🏆 Best Deal',
          category: 'Wearables',
          storesAvailable: ['Amazon', 'Flipkart'],
        ),
        BestDealModel(
          id: 'prod-5',
          title: 'Sony WH-1000XM5',
          brand: 'Sony',
          store: 'Amazon',
          imageUrl: 'assets/banners/headphone_3d.jpg',
          originalPrice: 29990,
          discountedPrice: 24990,
          discountPercentage: 17,
          cashbackPercentage: 7,
          cashbackAmount: 1800,
          couponCode: 'SONY1500',
          couponDiscount: 1500,
          effectiveSavings: 8300,
          effectivePrice: 21690,
          isBestDeal: true,
          badge: '🏆 Best Deal',
          category: 'Audio',
          storesAvailable: ['Amazon', 'Croma', 'Flipkart'],
        ),
      ],
      offers: const [
        HomeOfferModel(
          id: 'off-1',
          store: 'Myntra',
          storeLogo: 'assets/cards/myntra.jpg',
          title: 'Extra 20% OFF on Top Footwear & Streetwear',
          discount: 'Extra 20% OFF',
          cashback: '10% Cashback',
          cashbackRate: 10.0,
          validity: 'Ends in 2 days',
          imageUrl: 'assets/cards/col_myntra.jpg',
          category: 'Fashion',
          actionUrl: 'https://www.myntra.com',
        ),
        HomeOfferModel(
          id: 'off-2',
          store: 'Amazon',
          storeLogo: 'assets/cards/amazon.jpg',
          title: 'Mega Electronics Festival — Extra Cashback Rewards',
          discount: 'Up to 50% OFF',
          cashback: 'Up to 8% Cashback',
          cashbackRate: 8.0,
          validity: 'Limited Time',
          imageUrl: 'assets/cards/col_amazon.jpg',
          category: 'Electronics',
          actionUrl: 'https://www.amazon.in',
        ),
        HomeOfferModel(
          id: 'off-3',
          store: 'Nykaa',
          storeLogo: 'assets/cards/nykaa.jpg',
          title: 'Luxury Beauty & Skincare Gala with Flat ₹300 Reward',
          discount: 'Flat 40% OFF',
          cashback: 'Flat 12% Cashback',
          cashbackRate: 12.0,
          validity: 'Valid till Sunday',
          imageUrl: 'assets/cards/col_nykaa.jpg',
          category: 'Beauty',
          actionUrl: 'https://www.nykaa.com',
        ),
        HomeOfferModel(
          id: 'off-4',
          store: 'AJIO',
          storeLogo: 'assets/cards/ajio-coupons.jpg',
          title: 'Trendsetter Fashion Fest — Flat 50% to 90% OFF',
          discount: 'Up to 90% OFF',
          cashback: 'Up to 10% Cashback',
          cashbackRate: 10.0,
          validity: 'Limited Time',
          imageUrl: 'assets/cards/col_ajio.jpg',
          category: 'Fashion',
          actionUrl: 'https://www.ajio.com',
        ),
        HomeOfferModel(
          id: 'off-5',
          store: 'The Derma Co',
          storeLogo: 'assets/cards/thedermaco-coupons.jpg',
          title: 'Dermatologist Designed Skincare — Buy 2 Get 2 Free',
          discount: 'Buy 2 Get 2',
          cashback: 'Up to 18% Cashback',
          cashbackRate: 18.0,
          validity: 'Weekend Special',
          imageUrl: 'assets/cards/col_derma.jpg',
          category: 'Beauty',
          actionUrl: 'https://thedermaco.com',
        ),
        HomeOfferModel(
          id: 'off-6',
          store: 'Dot & Key',
          storeLogo: 'assets/cards/dotandkey-coupons.png',
          title: 'Ceramides & Fruit Actives — Flat 20% OFF + 12% Cashback',
          discount: 'Flat 20% OFF',
          cashback: 'Up to 12% Cashback',
          cashbackRate: 12.0,
          validity: 'Active Today',
          imageUrl: 'assets/cards/col_dotkey.jpg',
          category: 'Beauty',
          actionUrl: 'https://www.dotandkey.com',
        ),
        HomeOfferModel(
          id: 'off-7',
          store: 'boAt',
          storeLogo: 'assets/cards/boat-coupon.jpg',
          title: 'Immersion Audio Fest — Up to 75% OFF on ANC Headphones',
          discount: 'Up to 75% OFF',
          cashback: 'Up to 8% Cashback',
          cashbackRate: 8.0,
          validity: 'Valid till 30 Sep',
          imageUrl: 'assets/banners/headphone_banner_16_9.jpg',
          category: 'Electronics',
          actionUrl: 'https://www.boat-lifestyle.com',
        ),
        HomeOfferModel(
          id: 'off-8',
          store: 'Shopsy',
          storeLogo: 'assets/cards/shopsy-coupons.png',
          title: 'Budget Shopping Extravaganza — Deals from ₹49',
          discount: 'Starting ₹49',
          cashback: 'Up to 7.50% Cashback',
          cashbackRate: 7.5,
          validity: 'Ongoing Fest',
          imageUrl: 'assets/cards/col_shopsy.jpg',
          category: 'Shopping',
          actionUrl: 'https://www.shopsy.in',
        ),
      ],
      coupons: const [
        HomeCouponModel(
          id: 'cp-1',
          code: 'MYNTRA500',
          store: 'Myntra',
          discount: '₹500 OFF',
          minOrder: 2499,
          cashback: 'Up to 10%',
          validity: 'Valid till 30 Sep',
          description: 'Applicable on orders above ₹2,499 across all footwear and apparel',
          applicableOn: 'Men, Women & Kids Footwear, Sneakers & Apparel',
          successRate: '99% Success Rate',
          terms: [
            'Valid on minimum order value of ₹2,499.',
            'Applicable on selected footwear, clothing & fashion accessories.',
            'Can be used once per user account.',
            'Extra cashback up to 10% will be credited to KashIQ wallet.',
          ],
        ),
        HomeCouponModel(
          id: 'cp-2',
          code: 'AJIOMAN10',
          store: 'AJIO',
          discount: '10% OFF',
          minOrder: 1999,
          cashback: 'Up to 12%',
          validity: 'Valid till 15 Oct',
          description: 'Extra 10% instant discount on premium fashion brands on AJIO',
          applicableOn: 'Premium Fashion Brands, Denim, Shirts & Ethnic Wear',
          successRate: '97% Success Rate',
          terms: [
            'Flat 10% instant discount on orders above ₹1,999.',
            'Valid across AJIO Trendsetter and international brands.',
            'KashIQ extra cashback credited within 48 hours of order confirmation.',
          ],
        ),
        HomeCouponModel(
          id: 'cp-3',
          code: 'AMZTECH250',
          store: 'Amazon',
          discount: '₹250 OFF',
          minOrder: 1500,
          cashback: 'Up to 8%',
          validity: 'Valid today only',
          description: 'Instant discount voucher on computer accessories and audio gear',
          applicableOn: 'Electronics, Audio Headphones, Wireless Earbuds & PC Gear',
          successRate: '98% Success Rate',
          terms: [
            'Instant ₹250 savings at Amazon payment checkout.',
            'Minimum cart value of ₹1,500 required.',
            'Valid for all payment modes including UPI, Credit & Debit Cards.',
          ],
        ),
        HomeCouponModel(
          id: 'cp-4',
          code: 'FLIPKART400',
          store: 'Flipkart',
          discount: '₹400 OFF',
          minOrder: 2999,
          cashback: 'Up to 6%',
          validity: 'Valid till 28 Sep',
          description: 'Flat ₹400 voucher on home appliances and kitchen gadgets',
          applicableOn: 'Small Appliances, Kitchen Cookware & Home Utilities',
          successRate: '96% Success Rate',
          terms: [
            'Valid on home & kitchen category orders above ₹2,999.',
            'One redemption allowed per verified Flipkart account.',
            'Cashback tracked automatically via KashIQ redirect link.',
          ],
        ),
      ],
      smartSavings: const [
        SmartSavingsModel(
          id: 'ss-1',
          productName: 'Sony WH-1000XM5 ANC Headphones',
          brand: 'Sony',
          imageUrl: 'assets/banners/headphone_banner_16_9.jpg',
          productPrice: 29990,
          storeDiscount: 4000,
          couponDiscount: 1500,
          bankDiscount: 0,
          cashback: 1800,
          totalSavings: 7300,
          effectivePrice: 22690,
          isBestDeal: true,
          bestStore: 'Amazon',
          stores: [
            StoreDealComparison(
              store: 'Amazon',
              price: 25990,
              storeDiscount: 4000,
              cashback: 1800,
              coupon: 1500,
              effectivePrice: 22690,
              savings: 7300,
              isBest: true,
            ),
            StoreDealComparison(
              store: 'Croma',
              price: 26990,
              storeDiscount: 3000,
              cashback: 1200,
              coupon: 1000,
              effectivePrice: 24790,
              savings: 5200,
              isBest: false,
            ),
          ],
        ),
        SmartSavingsModel(
          id: 'ss-2',
          productName: 'Dyson V8 Absolute Cordless Vacuum',
          brand: 'Dyson',
          imageUrl: 'assets/cards/dyson-discount-codes.jpg',
          productPrice: 39900,
          storeDiscount: 6000,
          couponDiscount: 2000,
          bankDiscount: 0,
          cashback: 2400,
          totalSavings: 10400,
          effectivePrice: 29500,
          isBestDeal: true,
          bestStore: 'Dyson',
          stores: [
            StoreDealComparison(
              store: 'Dyson',
              price: 33900,
              storeDiscount: 6000,
              cashback: 2400,
              coupon: 2000,
              effectivePrice: 29500,
              savings: 10400,
              isBest: true,
            ),
            StoreDealComparison(
              store: 'Amazon',
              price: 35900,
              storeDiscount: 4000,
              cashback: 1500,
              coupon: 1000,
              effectivePrice: 31900,
              savings: 8000,
              isBest: false,
            ),
          ],
        ),
      ],
      featuredStores: const [
        FeaturedStoreModel(
          id: 'st-1',
          name: 'Amazon',
          logoUrl: 'assets/cards/amazon.jpg',
          cashbackRate: 'Up to 8% Cashback',
          maxCashback: 8.0,
          offerTag: 'Top Retailer',
          totalOffers: 120,
          totalCoupons: 45,
          websiteUrl: 'https://www.amazon.in',
        ),
        FeaturedStoreModel(
          id: 'st-2',
          name: 'Myntra',
          logoUrl: 'assets/cards/myntra.jpg',
          cashbackRate: 'Up to 12% Cashback',
          maxCashback: 12.0,
          offerTag: 'Fashion Hub',
          totalOffers: 85,
          totalCoupons: 32,
          websiteUrl: 'https://www.myntra.com',
        ),
        FeaturedStoreModel(
          id: 'st-3',
          name: 'AJIO',
          logoUrl: 'assets/cards/ajio-coupons.jpg',
          cashbackRate: 'Up to 10% Cashback',
          maxCashback: 10.0,
          offerTag: 'Trends Sale',
          totalOffers: 65,
          totalCoupons: 28,
          websiteUrl: 'https://www.ajio.com',
        ),
        FeaturedStoreModel(
          id: 'st-4',
          name: 'Flipkart',
          logoUrl: 'assets/cards/flipkart-electronics.png',
          cashbackRate: 'Up to 6.50% Cashback',
          maxCashback: 6.5,
          offerTag: 'Billion Deals',
          totalOffers: 110,
          totalCoupons: 39,
          websiteUrl: 'https://www.flipkart.com',
        ),
        FeaturedStoreModel(
          id: 'st-5',
          name: 'Nykaa',
          logoUrl: 'assets/cards/nykaa.jpg',
          cashbackRate: 'Up to 15% Cashback',
          maxCashback: 15.0,
          offerTag: 'Beauty Fest',
          totalOffers: 45,
          totalCoupons: 19,
          websiteUrl: 'https://www.nykaa.com',
        ),
        FeaturedStoreModel(
          id: 'st-6',
          name: 'boAt',
          logoUrl: 'assets/cards/boat-coupon.jpg',
          cashbackRate: 'Up to 8% Cashback',
          maxCashback: 8.0,
          offerTag: 'Audio Star',
          totalOffers: 35,
          totalCoupons: 14,
          websiteUrl: 'https://www.boat-lifestyle.com',
        ),
        FeaturedStoreModel(
          id: 'st-7',
          name: 'The Derma Co',
          logoUrl: 'assets/cards/thedermaco-coupons.jpg',
          cashbackRate: 'Up to 18% Cashback',
          maxCashback: 18.0,
          offerTag: 'Skincare Hub',
          totalOffers: 28,
          totalCoupons: 12,
          websiteUrl: 'https://thedermaco.com',
        ),
        FeaturedStoreModel(
          id: 'st-8',
          name: 'Dot & Key',
          logoUrl: 'assets/cards/dotandkey-coupons.png',
          cashbackRate: 'Up to 12% Cashback',
          maxCashback: 12.0,
          offerTag: 'Clean Glow',
          totalOffers: 22,
          totalCoupons: 10,
          websiteUrl: 'https://www.dotandkey.com',
        ),
        FeaturedStoreModel(
          id: 'st-9',
          name: 'Cleartrip',
          logoUrl: 'assets/cards/cleartrip.png',
          cashbackRate: 'Up to 8% Cashback',
          maxCashback: 8.0,
          offerTag: 'Travel Special',
          totalOffers: 30,
          totalCoupons: 15,
          websiteUrl: 'https://www.cleartrip.com',
        ),
        FeaturedStoreModel(
          id: 'st-10',
          name: 'Tata CLiQ',
          logoUrl: 'assets/cards/tatacliq-coupons.png',
          cashbackRate: 'Up to 6% Cashback',
          maxCashback: 6.0,
          offerTag: 'Luxury Hub',
          totalOffers: 40,
          totalCoupons: 18,
          websiteUrl: 'https://www.tatacliq.com',
        ),
      ],
      trendingDeals: const [
        TrendingDealModel(
          id: 'td-1',
          brand: 'Nike',
          productName: 'Nike Air Jordan 1 Low Retro',
          price: 7999,
          originalPrice: 10295,
          discount: '22% OFF',
          cashback: '₹650 Cashback',
          cashbackAmount: 650,
          savingAmount: '₹2,946',
          badge: '🔥 Trending',
          urgency: 'Selling Fast',
          imageUrl: 'assets/banners/sneaker_banner_16_9.jpg',
          store: 'Myntra',
        ),
        TrendingDealModel(
          id: 'td-2',
          brand: 'boAt',
          productName: 'boAt Airdopes 141 ANC Earbuds',
          price: 1299,
          originalPrice: 4490,
          discount: '71% OFF',
          cashback: '₹120 Cashback',
          cashbackAmount: 120,
          savingAmount: '₹3,311',
          badge: '🔥 Trending',
          urgency: 'Hot Deal',
          imageUrl: 'assets/cards/boat-coupon.jpg',
          store: 'Flipkart',
        ),
        TrendingDealModel(
          id: 'td-3',
          brand: 'Noise',
          productName: 'Noise ColorFit Icon Buzz Smartwatch',
          price: 1999,
          originalPrice: 4999,
          discount: '60% OFF',
          cashback: '₹150 Cashback',
          cashbackAmount: 150,
          savingAmount: '₹3,150',
          badge: '🔥 Trending',
          urgency: 'Limited Stock',
          imageUrl: 'assets/cards/gonoise-coupons.jpg',
          store: 'Amazon',
        ),
        TrendingDealModel(
          id: 'td-4',
          brand: 'Dot & Key',
          productName: 'Dot & Key Barrier Repair Ceramides Cream',
          price: 395,
          originalPrice: 595,
          discount: '34% OFF',
          cashback: '₹50 Cashback',
          cashbackAmount: 50,
          savingAmount: '₹250',
          badge: '🔥 Trending',
          urgency: 'Popular',
          imageUrl: 'assets/cards/dotandkey-coupons.png',
          store: 'Nykaa',
        ),
        TrendingDealModel(
          id: 'td-5',
          brand: 'The Derma Co',
          productName: 'The Derma Co 10% Niacinamide Serum',
          price: 499,
          originalPrice: 699,
          discount: '28% OFF',
          cashback: '₹75 Cashback',
          cashbackAmount: 75,
          savingAmount: '₹275',
          badge: '🔥 Trending',
          urgency: 'Bestseller',
          imageUrl: 'assets/cards/thedermaco-coupons.jpg',
          store: 'Nykaa',
        ),
        TrendingDealModel(
          id: 'td-6',
          brand: 'Aqualogica',
          productName: 'Aqualogica Glow+ Dewy Sunscreen SPF 50',
          price: 349,
          originalPrice: 499,
          discount: '30% OFF',
          cashback: '₹40 Cashback',
          cashbackAmount: 40,
          savingAmount: '₹190',
          badge: '🔥 Trending',
          urgency: 'Viral Hit',
          imageUrl: 'assets/cards/aqualogica-coupons.png',
          store: 'Amazon',
        ),
        TrendingDealModel(
          id: 'td-7',
          brand: 'mCaffeine',
          productName: 'mCaffeine Naked & Raw Coffee Face Scrub',
          price: 299,
          originalPrice: 449,
          discount: '33% OFF',
          cashback: '₹35 Cashback',
          cashbackAmount: 35,
          savingAmount: '₹185',
          badge: '🔥 Trending',
          urgency: 'Hot Deal',
          imageUrl: 'assets/cards/mcaffeine-coupons.jpg',
          store: 'Nykaa',
        ),
        TrendingDealModel(
          id: 'td-8',
          brand: 'Uniqlo',
          productName: 'Uniqlo Ultra Light Down Puffer Jacket',
          price: 4990,
          originalPrice: 6990,
          discount: '28% OFF',
          cashback: '₹350 Cashback',
          cashbackAmount: 350,
          savingAmount: '₹2,350',
          badge: '🔥 Trending',
          urgency: 'Winter Special',
          imageUrl: 'assets/cards/uniqlo-coupons.jpg',
          store: 'Uniqlo',
        ),
      ],
      priceDrops: const [
        PriceDropModel(
          id: 'pd-ipad-10',
          brand: 'Apple',
          productName: 'Apple iPad 10th Gen (64GB, Wi-Fi)',
          wasPrice: 44900,
          nowPrice: 32900,
          priceDropAmount: 12000,
          priceDropBadge: '₹12,000 Price Drop',
          cashback: '₹990 Cashback',
          cashbackAmount: 990,
          store: 'Amazon',
          imageUrl: 'assets/banners/phone_banner_16_9.jpg',
        ),
        PriceDropModel(
          id: 'pd-bose-qc45',
          brand: 'Bose',
          productName: 'Bose QuietComfort 45',
          wasPrice: 29900,
          nowPrice: 17900,
          priceDropAmount: 12000,
          priceDropBadge: '₹12,000 Price Drop',
          cashback: '₹540 Cashback',
          cashbackAmount: 540,
          store: 'Amazon',
          imageUrl: 'assets/banners/headphone_3d.jpg',
        ),
      ],
      cashbackIncreases: const [
        CashbackIncreaseModel(
          id: 'ci-1',
          store: 'Myntra',
          logoUrl: 'assets/cards/myntra.jpg',
          previousRate: '5%',
          newRate: '12%',
          headline: 'Cashback increased 5% → 12%',
          badge: '🔥 Limited-time increase',
          description: 'Earn massive 12% real wallet cashback on all summer apparel and sneakers.',
        ),
        CashbackIncreaseModel(
          id: 'ci-2',
          store: 'AJIO',
          logoUrl: 'assets/cards/ajio-coupons.jpg',
          previousRate: '8%',
          newRate: '15%',
          headline: 'Cashback increased 8% → 15%',
          badge: '🔥 Limited-time increase',
          description: 'Special weekend boost: 15% cashback applied automatically at checkout.',
        ),
      ],
    );
  }
}
