// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxCyfMzI27VrJrOZfE7aFn-hR0mSabMyc',
    appId: '1:429532715808:web:971b13ba20ebececbf1545',
    messagingSenderId: '429532715808',
    projectId: 'cashback-reward-app',
    authDomain: 'cashback-reward-app.firebaseapp.com',
    storageBucket: 'cashback-reward-app.firebasestorage.app',
    measurementId: 'G-Q05EH4DG9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyeOXhEOEMA6Fwo44RGqwB_TSwtd1S7OU',
    appId: '1:429532715808:android:6f09ab507a4f5318bf1545',
    messagingSenderId: '429532715808',
    projectId: 'cashback-reward-app',
    storageBucket: 'cashback-reward-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzqOrOO7S_Iaqk4fzUyXaUaTsuwYWy0E4',
    appId: '1:429532715808:ios:ce391696d967f602bf1545',
    messagingSenderId: '429532715808',
    projectId: 'cashback-reward-app',
    storageBucket: 'cashback-reward-app.firebasestorage.app',
    iosBundleId: 'com.example.cashbackRewardApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzqOrOO7S_Iaqk4fzUyXaUaTsuwYWy0E4',
    appId: '1:429532715808:ios:ce391696d967f602bf1545',
    messagingSenderId: '429532715808',
    projectId: 'cashback-reward-app',
    storageBucket: 'cashback-reward-app.firebasestorage.app',
    iosBundleId: 'com.example.cashbackRewardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxCyfMzI27VrJrOZfE7aFn-hR0mSabMyc',
    appId: '1:429532715808:web:1ec18f49b60b8d44bf1545',
    messagingSenderId: '429532715808',
    projectId: 'cashback-reward-app',
    authDomain: 'cashback-reward-app.firebaseapp.com',
    storageBucket: 'cashback-reward-app.firebasestorage.app',
    measurementId: 'G-M91PS5SV49',
  );
}
